name: CI


on:
push:
branches: [ main ]
pull_request:
branches: [ main ]


jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Set up Python
uses: actions/setup-python@v4
with:
python-version: '3.11'
- name: Install dependencies
run: pip install -r requirements.txt
- name: Lint check (basic)
run: python -m pyflakes extract_passport_from_pdf.py || true
